services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: pnpm run start:dev
    env_file:
      - .env
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: codecon_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
